name: Glitch Sync

on:
    push:
        branches:
            - main

jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - name: Sync to Glitch
              uses: wei/git-sync@v3
              with:
                  source_repo: https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
                  source_branch: main
                  destination_repo: ${{ secrets.GLITCH_GIT_URL }}
                  destination_branch: main

            - name: Install dependencies and run build
              run: |
                  cd /app/
                  npm install
                  npm run build
